// Shared resource registry — powers the Resources listing and the per-tool
// detail pages at /resources/:slug. Each link carries:
//   slug  — URL-safe identifier (derived from the tool name)
//   usage — short "how we use it" paragraph (unique per tool, used for SEO meta)
//   tags  — tags used to match related blog posts
import { Boxes, Shield, Terminal, Code, BookOpen, Network, Brain, Users, Wallet, HardDrive, Palette, Server } from "lucide-react";

export const slugify = (name) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const RAW_GROUPS = [
  {
    icon: Boxes,
    title: "Blockchain & Web3",
    links: [
      { name: "Ethereum Docs", url: "https://ethereum.org/developers", desc: "Official Ethereum developer documentation.", usage: "Our first stop for protocol changes, EIP summaries, and JSON-RPC references whenever a tutorial needs up-to-date mainnet behavior.", tags: ["Ethereum", "Blockchain"] },
      { name: "Solidity Language", url: "https://docs.soliditylang.org", desc: "Smart contract programming language reference.", usage: "We check the Solidity docs before writing any contract example, so every snippet in our tutorials compiles against the current compiler version.", tags: ["Solidity", "Smart Contracts"] },
      { name: "Ethers.js", url: "https://docs.ethers.org", desc: "JavaScript library for Ethereum interaction.", usage: "The library behind most of our JavaScript contract examples — providers, signers, and contract calls all follow the ethers pattern.", tags: ["Ethereum", "Smart Contracts", "Web3"] },
      { name: "web3.js", url: "https://web3js.readthedocs.io", desc: "Ethereum JavaScript API and quorum extensions.", usage: "We reference web3.js for older integrations and private-network tutorials where web3js-quorum is still the standard.", tags: ["Web3", "Ethereum", "Smart Contracts"] },
      { name: "Foundry / Cast", url: "https://book.getfoundry.sh", desc: "Modern EVM development toolkit and CLI.", usage: "Cast and forge are our go-to CLI tools for quick chain queries and fast contract testing in tutorials.", tags: ["Smart Contracts", "Ethereum", "CLI"] },
      { name: "Hardhat", url: "https://hardhat.org", desc: "Ethereum development environment for professionals.", usage: "Our contract development walkthroughs lean on Hardhat for local networks, deployment scripts, and plugin-based testing.", tags: ["Smart Contracts", "Ethereum"] },
      { name: "OpenZeppelin", url: "https://docs.openzeppelin.com", desc: "Audited smart contract libraries and security standards.", usage: "We never hand-roll ERC standards — our tutorials import OpenZeppelin's audited contracts and follow their security guides.", tags: ["Smart Contracts", "Ethereum", "Security"] },
      { name: "Kaspa WIKI", url: "https://kas.fyi", desc: "Kaspa protocol docs and node guides.", usage: "The kas.fyi wiki is our reference for node setup flags, wallet commands, and protocol details in every Kaspa guide we publish.", tags: ["Kaspa", "Blockchain", "Node"] },
      { name: "rusty-kaspa", url: "https://github.com/kaspanet/rusty-kaspa", desc: "Rust implementation of the Kaspa node.", usage: "We build rusty-kaspa from source in our full Kaspa node guide — it powers kaspad, the wallet CLI, and the RPC setup.", tags: ["Kaspa", "Rust", "Node", "RPC"] },
      { name: "Solana Web3.js", url: "https://solana-labs.github.io/solana-web3.js", desc: "Solana JavaScript SDK.", usage: "Used in our Solana quickstart to connect to devnet, airdrop SOL, and send that first transaction.", tags: ["Solana", "Web3", "JavaScript"] },
      { name: "Solana Docs", url: "https://docs.solana.com", desc: "Official Solana developer documentation.", usage: "The official docs we cite whenever we cover Solana accounts, transactions, and program deployment.", tags: ["Solana", "Blockchain"] },
      { name: "TRON / SunSwap", url: "https://developers.tron.network", desc: "TRON network developer docs and DEX guides.", usage: "Our SunSwap trading guide follows the TRON developer docs for wallet integration and contract calls.", tags: ["SunSwap", "TRON", "DeFi"] },
      { name: "Etherscan", url: "https://etherscan.io", desc: "Ethereum block explorer and contract verification.", usage: "We use Etherscan to verify contracts in our tutorials and to show readers how to trace transactions safely.", tags: ["Ethereum", "Crypto"] },
      { name: "Chainlink", url: "https://docs.chain.link", desc: "Decentralized oracle networks and data feeds.", usage: "Referenced when we explain oracles and how contracts consume off-chain price feeds.", tags: ["Smart Contracts", "Blockchain"] },
      { name: "The Graph", url: "https://thegraph.com/docs", desc: "Indexing and querying blockchain data with GraphQL.", usage: "Our go-to for querying indexed blockchain data with GraphQL instead of scraping raw RPC calls.", tags: ["Web3", "Blockchain"] },
      { name: "IPFS Docs", url: "https://docs.ipfs.tech", desc: "InterPlanetary File System documentation.", usage: "Our IPFS upload-and-retrieve walkthrough is built directly on this documentation — install, add, pin, and fetch by hash.", tags: ["IPFS", "Decentralized Storage", "Web3"] },
      { name: "Filecoin", url: "https://docs.filecoin.io", desc: "Decentralized storage network built on IPFS.", usage: "We point readers here when a decentralized-storage tutorial needs persistent, incentivized storage on top of IPFS.", tags: ["IPFS", "Decentralized Storage"] },
      { name: "Arweave", url: "https://docs.arweave.org", desc: "Permanent, decentralized data storage.", usage: "Referenced for permanent-storage patterns where data must outlive any single node.", tags: ["Decentralized Storage", "Web3"] },
      { name: "Hardhat Toolbox", url: "https://hardhat.org/hardhat-toolbox", desc: "Bundled Hardhat plugins for testing and deployment.", usage: "The bundled plugin set we recommend in setup tutorials so testing, coverage, and deployment work out of the box.", tags: ["Smart Contracts", "Ethereum"] },
      { name: "Alchemy", url: "https://www.alchemy.com", desc: "Web3 developer platform with RPC, APIs, and enhanced dashboards.", usage: "One of the RPC platforms we suggest when tutorials need a hosted Ethereum endpoint instead of a local node.", tags: ["Ethereum", "Web3"] },
      { name: "Infura", url: "https://www.infura.io", desc: "Scalable RPC access to Ethereum, IPFS, and L2s.", usage: "Referenced as a scalable RPC option for Ethereum and IPFS access without running your own infrastructure.", tags: ["Ethereum", "IPFS"] },
      { name: "QuickNode", url: "https://www.quicknode.com", desc: "Fast, reliable blockchain nodes and APIs.", usage: "Recommended when a tutorial needs fast, reliable node access across multiple chains.", tags: ["Blockchain", "Node"] },
      { name: "Helius", url: "https://www.helius.dev", desc: "Solana RPC, enhanced APIs, and webhooks.", usage: "Cited in our Solana tutorials for enhanced APIs and webhooks that raw RPC doesn't provide.", tags: ["Solana", "Web3"] },
      { name: "WalletConnect", url: "https://walletconnect.com", desc: "Open protocol to connect wallets to dApps.", usage: "The protocol we reference when a dApp tutorial needs wallet connections on mobile.", tags: ["Web3", "Crypto"] },
      { name: "RainbowKit", url: "https://rainbowkit.com", desc: "Drop-in wallet connection UI for React.", usage: "Our preferred drop-in wallet UI for React dApp examples — a few lines and wallet connection just works.", tags: ["Web3", "JavaScript"] },
      { name: "Tenderly", url: "https://tenderly.co", desc: "Simulation, monitoring, and debugging for smart contracts.", usage: "Used in debugging walkthroughs to simulate transactions and trace why a contract call reverted.", tags: ["Smart Contracts", "Ethereum"] },
      { name: "Moralis", url: "https://moralis.io", desc: "Backend APIs for cross-chain Web3 apps.", usage: "Referenced for cross-chain backend APIs when a tutorial needs indexed data fast.", tags: ["Web3", "Blockchain"] },
      { name: "DefiLlama", url: "https://defillama.com", desc: "TVL and DeFi protocol analytics across chains.", usage: "Our source for TVL charts and protocol comparisons whenever we cover DeFi trends.", tags: ["DeFi", "Crypto"] },
    ],
  },
  {
    icon: Wallet,
    title: "Crypto Utilities & Wallets",
    links: [
      { name: "Bitcoin Core", url: "https://bitcoincore.org", desc: "Reference Bitcoin client and full-node docs.", usage: "bitcoincore.org anchors our full-node guide — we verify releases, run bitcoind, and send via bitcoin-cli exactly as documented here.", tags: ["Bitcoin", "Bitcoin Core", "Full Node"] },
      { name: "Monero", url: "https://www.getmonero.org/resources/developer-guides", desc: "Monero developer guides and CLI reference.", usage: "The developer guides behind our Monero CLI tutorials — daemon sync, wallet setup, and solo-mining fixes.", tags: ["Monero", "XMR", "Crypto"] },
      { name: "kaspawallet CLI", url: "https://github.com/kaspanet/rusty-kaspa#wallet", desc: "Command-line Kaspa wallet for sending transactions.", usage: "We use kaspawallet in our command-line crypto guide to send Kaspa transactions from a synced local node.", tags: ["Kaspa", "CLI", "Crypto"] },
      { name: "MetaMask", url: "https://metamask.io", desc: "Browser wallet for Ethereum and EVM chains.", usage: "Referenced whenever a tutorial walks through connecting a browser wallet to a dApp or test network.", tags: ["Web3", "Ethereum"] },
      { name: "Rabby Wallet", url: "https://rabby.io", desc: "Multi-chain wallet with clear transaction previews.", usage: "Recommended for its pre-sign transaction previews when we teach safe approval hygiene.", tags: ["Crypto", "Security"] },
      { name: "CoinGecko", url: "https://www.coingecko.com", desc: "Crypto prices, market caps, and on-chain stats.", usage: "Our quick reference for prices and market stats when a tutorial needs real-time context.", tags: ["Crypto", "Blockchain"] },
      { name: "CoinMarketCap", url: "https://coinmarketcap.com", desc: "Cryptocurrency market data and rankings.", usage: "Used for rankings and market-cap context in our crypto onboarding articles.", tags: ["Crypto"] },
      { name: "DefiLlama", url: "https://defillama.com", desc: "Total value locked and DeFi protocol analytics.", usage: "We pull TVL and yield numbers from here for our DeFi explainers.", tags: ["DeFi", "Crypto"] },
      { name: "Dune Analytics", url: "https://dune.com", desc: "Build and share SQL queries over blockchain data.", usage: "We point data-driven readers here to query on-chain data with SQL instead of one-off scripts.", tags: ["Crypto", "Web3"] },
      { name: "Gas Now", url: "https://ethgasstation.info", desc: "Real-time Ethereum gas price tracker.", usage: "Checked before publishing any Ethereum tutorial so fee estimates stay realistic.", tags: ["Ethereum"] },
      { name: "Etherscan Gas Tracker", url: "https://etherscan.io/gastracker", desc: "Live Ethereum gas fees and historical charts.", usage: "Referenced in guides for live gas context and historical fee charts.", tags: ["Ethereum"] },
      { name: "revoke.cash", url: "https://revoke.cash", desc: "Review and revoke token spend approvals.", usage: "A tool we recommend in every approval-safety tutorial — review and revoke token spend approvals before they bite you.", tags: ["Security", "Crypto"] },
      { name: "DeBank", url: "https://debank.com", desc: "Portfolio tracker across DeFi protocols and chains.", usage: "Used for portfolio-tracking walkthroughs across DeFi positions.", tags: ["DeFi", "Crypto"] },
      { name: "Zapper", url: "https://zapper.fi", desc: "Track wallets, DeFi positions, and NFTs in one dashboard.", usage: "Referenced when a tutorial needs a single-dashboard view of wallets and positions.", tags: ["DeFi"] },
      { name: "Grass.io", url: "https://grass.io", desc: "Earn crypto by sharing unused internet bandwidth.", usage: "We reviewed Grass end-to-end — earning GRASS tokens by sharing unused bandwidth on a DePIN network.", tags: ["Grass", "DePIN", "Web3"] },
    ],
  },
  {
    icon: Shield,
    title: "Security & Privacy",
    links: [
      { name: "Tails OS", url: "https://tails.net", desc: "Amnesic incognito live operating system.", usage: "Tails is the operating system behind our bootable-USB and persistent-storage privacy guides.", tags: ["TailsOS", "Tails", "Privacy", "Tor", "Security"] },
      { name: "Tor Project", url: "https://www.torproject.org", desc: "Anonymous browsing and the Tor network.", usage: "Referenced whenever a privacy tutorial routes traffic through Tor.", tags: ["Tor", "Privacy"] },
      { name: "VirusTotal", url: "https://www.virustotal.com", desc: "Scan files and URLs against dozens of engines.", usage: "Our first stop in threat-analysis tutorials — scanning suspicious files against dozens of engines at once.", tags: ["VirusTotal", "Cybersecurity", "Security Tools"] },
      { name: "Shodan", url: "https://www.shodan.io", desc: "Search engine for internet-connected devices.", usage: "Used in our hidden-cybersecurity-toolkit piece to demonstrate exposed-device discovery.", tags: ["Shodan", "Cybersecurity", "Security Tools"] },
      { name: "Censys", url: "https://search.censys.io", desc: "Internet-wide scanning and asset discovery.", usage: "Referenced alongside Shodan for internet-wide asset scanning.", tags: ["Cybersecurity"] },
      { name: "Have I Been Pwned", url: "https://haveibeenpwned.com", desc: "Check if your email appears in data breaches.", usage: "We recommend it in every account-hygiene tutorial to check emails against known breaches.", tags: ["Cybersecurity", "Security"] },
      { name: "Google Advanced Protection", url: "https://landing.google.com/advancedprotection", desc: "Strongest Google account security for high-risk users.", usage: "Covered in a full article on the strongest Google account security for high-risk users.", tags: ["Google", "Authentication", "Cybersecurity"] },
      { name: "OWASP", url: "https://owasp.org", desc: "Open Web Application Security Project resources.", usage: "Our reference for web-app security standards whenever we write secure-development guidance.", tags: ["Cybersecurity", "Security"] },
      { name: "MITRE ATT&CK", url: "https://attack.mitre.org", desc: "Adversary tactics and techniques knowledge base.", usage: "Cited to map adversary tactics in our security explainers.", tags: ["Cybersecurity", "Security"] },
      { name: "CVE Database", url: "https://cve.mitre.org", desc: "Common Vulnerabilities and Exposures catalog.", usage: "We check CVE entries before recommending any software version in tutorials.", tags: ["Cybersecurity", "Security"] },
      { name: "NIST Cybersecurity", url: "https://www.nist.gov/cyberframework", desc: "NIST cybersecurity framework and guidelines.", usage: "Referenced for framework-based hardening checklists in our security articles.", tags: ["Cybersecurity"] },
      { name: "CISA Alerts", url: "https://www.cisa.gov/news-events/cybersecurity-advisories", desc: "US cyber agency advisories and bulletins.", usage: "Monitored for advisories that inform our security coverage.", tags: ["Cybersecurity", "Security"] },
      { name: "AbuseIPDB", url: "https://www.abuseipdb.com", desc: "Check and report malicious IP addresses.", usage: "Used in server-hardening tutorials to check and report malicious IPs before blocking or unbanning them.", tags: ["Security", "Server"] },
      { name: "URLScan.io", url: "https://urlscan.io", desc: "Scan and analyze suspicious websites safely.", usage: "Recommended for safely analyzing suspicious links before clicking them.", tags: ["Security Tools", "Security"] },
      { name: "Hybrid Analysis", url: "https://www.hybrid-analysis.com", desc: "Free malware analysis service with sandbox.", usage: "Our sandbox reference for detonating suspicious files in isolation.", tags: ["Cybersecurity", "Security Tools"] },
      { name: "Kali Linux", url: "https://www.kali.org", desc: "Penetration testing and security auditing distro.", usage: "Kali is the distro behind our penetration-testing tutorials — including running it on Windows 11 with WSL2 and Win-KeX.", tags: ["Kali Linux", "Kali", "Security", "WSL"] },
      { name: "Samsung Knox", url: "https://www.samsungknox.com", desc: "Defense-grade mobile security for Galaxy devices.", usage: "We wrote a full guide on Knox Suite enterprise security for Galaxy device fleets.", tags: ["Samsung Knox", "Knox Suite", "Mobile Security", "Enterprise"] },
    ],
  },
  {
    icon: Terminal,
    title: "Linux & DevOps",
    links: [
      { name: "Ubuntu Documentation", url: "https://help.ubuntu.com", desc: "Official Ubuntu server and desktop guides.", usage: "The official guides behind our Ubuntu server, storage, and desktop tutorials.", tags: ["Ubuntu", "Linux"] },
      { name: "Debian Reference", url: "https://www.debian.org/doc", desc: "Debian system administration manual.", usage: "Referenced in our Debian update and SSD-formatting guides for package-management and filesystem details.", tags: ["Debian", "Linux"] },
      { name: "Arch Wiki", url: "https://wiki.archlinux.org", desc: "In-depth Linux knowledge applicable to any distro.", usage: "We consult the Arch Wiki for deep Linux internals that apply to every distro we cover.", tags: ["Linux", "Command Line"] },
      { name: "Docker Docs", url: "https://docs.docker.com", desc: "Containerization engine and Compose reference.", usage: "Docker Docs is the backbone of our container series — install, Compose, networking, volumes, and logs all follow the official reference.", tags: ["Docker", "Containers", "DevOps"] },
      { name: "Docker Hub", url: "https://hub.docker.com", desc: "Container image registry and official images.", usage: "Where we pull base images for every container tutorial we publish.", tags: ["Docker", "Containers"] },
      { name: "systemd man pages", url: "https://www.freedesktop.org/software/systemd/man", desc: "Linux service management reference.", usage: "Our systemd service-management guide is built directly on these unit-file references.", tags: ["systemd", "Service", "Linux"] },
      { name: "UFW — Uncomplicated Firewall", url: "https://help.ubuntu.com/community/UFW", desc: "Simple firewall configuration for Ubuntu.", usage: "UFW anchors our 10-minute firewall-hardening walkthrough — allow rules, deny by default, verify.", tags: ["UFW", "Firewall", "Security", "Server"] },
      { name: "Nginx Documentation", url: "https://nginx.org/en/docs", desc: "Web server, reverse proxy, and load balancer.", usage: "Referenced in our Ubuntu hosting guide for reverse-proxy and TLS configuration.", tags: ["Nginx", "Hosting", "Server"] },
      { name: "Let's Encrypt", url: "https://letsencrypt.org", desc: "Free TLS/SSL certificates via certbot.", usage: "Every HTTPS tutorial we publish ends with a Let's Encrypt certificate.", tags: ["SSL", "HTTPS", "Security"] },
      { name: "Certbot", url: "https://certbot.eff.org", desc: "Automate Let's Encrypt certificate issuance.", usage: "Used alongside Let's Encrypt in our hosting walkthroughs to automate issuance and renewal.", tags: ["SSL", "HTTPS", "Linux"] },
      { name: "fail2ban", url: "https://github.com/fail2ban/fail2ban", desc: "Ban IPs that show malicious signs in logs.", usage: "Recommended in our SSH-hardening guide to auto-ban brute-force IPs.", tags: ["SSH", "Security", "Linux"] },
      { name: "tmux", url: "https://github.com/tmux/tmux/wiki", desc: "Terminal multiplexer for persistent sessions.", usage: "Our terminal-productivity tutorials use tmux for persistent sessions over SSH.", tags: ["Terminal", "Linux", "Command Line"] },
      { name: "GNU Bash Manual", url: "https://www.gnu.org/software/bash/manual", desc: "Bash shell reference and scripting guide.", usage: "The reference behind our bash one-liner and shell-scripting examples.", tags: ["bash", "Command Line", "Terminal"] },
      { name: "Linux Man Pages Online", url: "https://man7.org/linux/man-pages", desc: "Searchable Linux programmer manual pages.", usage: "We link readers here instead of paraphrasing flags in our command-line tutorials.", tags: ["Linux", "Command Line"] },
      { name: "Proxmox VE", url: "https://www.proxmox.com/en/proxmox-ve", desc: "Open-source virtualization and container management.", usage: "Referenced when a tutorial needs open-source VMs and container management on homelab hardware.", tags: ["Linux", "Server"] },
      { name: "Cockpit Project", url: "https://cockpit-project.org", desc: "Web-based graphical Linux server admin.", usage: "Recommended for web-based server admin in our Linux server guides.", tags: ["Linux", "Server"] },
    ],
  },
  {
    icon: Code,
    title: "Developer Tools",
    links: [
      { name: "Base44", url: "https://base44.com", desc: "Backend-as-a-service for building apps fast.", usage: "This very blog is built on Base44 — we use it to ship full apps with auth, database, and automations without managing infrastructure.", tags: ["Base44", "Web Development"] },
      { name: "GitHub", url: "https://github.com", desc: "Code hosting, version control, and CI/CD.", usage: "Our deployment pipelines push every project to GitHub first — including our GitHub Pages walkthrough.", tags: ["GitHub Pages", "Web Development"] },
      { name: "GitLab", url: "https://gitlab.com", desc: "DevOps platform with CI/CD and registries.", usage: "Referenced as a self-hostable alternative in our DevOps tutorials.", tags: ["DevOps"] },
      { name: "Bitbucket", url: "https://bitbucket.org", desc: "Git code hosting with Jira integration.", usage: "Cited when tutorials need Jira-integrated Git hosting.", tags: [] },
      { name: "Obsidian", url: "https://obsidian.md", desc: "Local-first Markdown knowledge base.", usage: "Obsidian gets a complete guide on this site — vaults, plugins, graph view, and AI integration for a local-first knowledge base.", tags: ["Obsidian", "Markdown", "Knowledge Management"] },
      { name: "Rufus", url: "https://rufus.ie", desc: "Create bootable USB drives on Windows.", usage: "We troubleshoot Rufus errors and build persistent live USBs with it in our bootable-media guides.", tags: ["Rufus", "USB", "Live USB", "Windows"] },
      { name: "BalenaEtcher", url: "https://etcher.balena.io", desc: "Flash OS images to SD cards and USB drives.", usage: "Our flashing tutorials use Etcher to write OS images to SD cards and SSDs.", tags: ["TailsOS", "SSD"] },
      { name: "MajorGeeks", url: "https://www.majorgeeks.com", desc: "Trusted source for free Windows software.", usage: "We reviewed MajorGeeks as a trusted source for free Windows software downloads.", tags: ["Windows", "Software", "Downloads"] },
      { name: "VS Code", url: "https://code.visualstudio.com/docs", desc: "Microsoft code editor documentation.", usage: "The editor in our web-development walkthroughs with recommended extensions for React and Tailwind.", tags: ["Web Development"] },
      { name: "Neovim", url: "https://neovim.io", desc: "Modern, extensible terminal text editor.", usage: "Referenced in terminal-first productivity setups in our command-line articles.", tags: ["Terminal", "Command Line"] },
      { name: "Postman", url: "https://www.postman.com", desc: "API development and testing workbench.", usage: "Used to test and document the APIs we build in tutorials.", tags: ["Web Development"] },
      { name: "Insomnia", url: "https://insomnia.rest", desc: "Open-source API client and design tool.", usage: "Recommended as an open-source API client in our API walkthroughs.", tags: [] },
      { name: "Vite", url: "https://vite.dev", desc: "Next-generation frontend build tooling.", usage: "The build tool powering every modern frontend project we publish, including this site.", tags: ["Web Development", "JavaScript"] },
      { name: "React Docs", url: "https://react.dev", desc: "Official React documentation and tutorials.", usage: "The canonical reference we cite in component and hooks tutorials.", tags: ["JavaScript", "Web Development"] },
      { name: "Tailwind CSS", url: "https://tailwindcss.com/docs", desc: "Utility-first CSS framework reference.", usage: "Every interface on this site is styled with Tailwind — our utility-first tutorials follow the official docs.", tags: ["Web Development"] },
      { name: "shadcn/ui", url: "https://ui.shadcn.com", desc: "Reusable component library for React.", usage: "The component library behind this blog's interface, cited in our React build guides.", tags: ["Web Development"] },
      { name: "regex101", url: "https://regex101.com", desc: "Build and debug regular expressions with explanations.", usage: "We build and debug every regular expression in our tutorials here before shipping it.", tags: [] },
      { name: "DevDocs", url: "https://devdocs.io", desc: "Combined, searchable API documentation.", usage: "Referenced as a fast way to search many API docs at once in our workflow articles.", tags: [] },
    ],
  },
  {
    icon: Network,
    title: "Networking & Infrastructure",
    links: [
      { name: "Cloudflare", url: "https://www.cloudflare.com", desc: "CDN, DNS, DDoS protection, and edge workers.", usage: "Used in our hosting tutorials for DNS and DDoS protection in front of origin servers.", tags: ["Hosting", "Deployment"] },
      { name: "Hetzner Cloud", url: "https://www.hetzner.com/cloud", desc: "Affordable European VPS and bare-metal hosting.", usage: "Recommended when a tutorial needs affordable, reliable VPS hosting for nodes and websites.", tags: ["VPS", "Hosting", "Server"] },
      { name: "DigitalOcean", url: "https://www.digitalocean.com", desc: "Developer-friendly cloud droplets and apps.", usage: "Cited in our server-setup guides as a developer-friendly cloud for quick deployments.", tags: ["Hosting", "Deployment"] },
      { name: "Linode / Akamai", url: "https://www.linode.com", desc: "Linux cloud computing and storage.", usage: "An alternative VPS provider we reference in Linux server tutorials.", tags: ["VPS", "Linux"] },
      { name: "Tailscale", url: "https://tailscale.com", desc: "Zero-config WireGuard mesh VPN.", usage: "Our preferred WireGuard mesh VPN for securely reaching homelab and cloud machines.", tags: [] },
      { name: "WireGuard", url: "https://www.wireguard.com", desc: "Fast, modern VPN protocol.", usage: "Referenced for fast, modern VPN setups in our networking guides.", tags: [] },
      { name: "Pi-hole", url: "https://pi-hole.net", desc: "Network-wide ad blocking DNS sinkhole.", usage: "Recommended in our self-hosting series for network-wide ad blocking.", tags: [] },
      { name: "NextDNS", url: "https://nextdns.io", desc: "Cloud-based DNS filtering and privacy.", usage: "Cited as a cloud alternative to Pi-hole in our privacy tutorials.", tags: [] },
      { name: "Fastly", url: "https://www.fastly.com", desc: "Edge cloud and content delivery network.", usage: "Referenced when tutorials cover edge CDN delivery.", tags: [] },
      { name: "UptimeRobot", url: "https://uptimerobot.com", desc: "Free uptime monitoring and alerts.", usage: "We recommend it to monitor the servers and nodes set up in our tutorials.", tags: [] },
      { name: "ntop", url: "https://www.ntop.org", desc: "Network traffic monitoring and analysis.", usage: "Used in our network traffic analysis walkthroughs.", tags: [] },
    ],
  },
  {
    icon: Brain,
    title: "AI & LLM Tools",
    links: [
      { name: "OpenAI Platform", url: "https://platform.openai.com/docs", desc: "GPT models, embeddings, and API reference.", usage: "Referenced in our AI tutorials for GPT model APIs, embeddings, and structured outputs.", tags: ["AI"] },
      { name: "Anthropic API", url: "https://docs.anthropic.com", desc: "Claude model documentation and guides.", usage: "The Claude API docs we consult for prompting and instruction-format articles.", tags: ["AI", "Prompts"] },
      { name: "Google Gemini", url: "https://ai.google.dev", desc: "Gemini models and AI APIs.", usage: "Covered in our guide to writing model instructions across Gemini, Base44, and Copilot.", tags: ["Gemini", "AI", "Google"] },
      { name: "LangChain", url: "https://python.langchain.com", desc: "Framework for LLM-powered applications.", usage: "Cited when a tutorial chains LLM calls into a working application.", tags: ["AI"] },
      { name: "LlamaIndex", url: "https://docs.llamaindex.ai", desc: "Data framework for RAG and agents.", usage: "Referenced for RAG pipelines that ground model answers in your own data.", tags: ["AI"] },
      { name: "Ollama", url: "https://ollama.com", desc: "Run LLMs locally on your own machine.", usage: "Our local-LLM tutorials run models with a single Ollama command.", tags: ["AI", "LLMs"] },
      { name: "Hugging Face", url: "https://huggingface.co", desc: "Model hub, datasets, and Spaces demos.", usage: "Hugging Face gets a complete guide on this site — the Hub, Transformers, datasets, Spaces, and the pro tips that make you faster.", tags: ["Hugging Face", "Machine Learning", "LLMs"] },
      { name: "MCP Specification", url: "https://modelcontextprotocol.io", desc: "Model Context Protocol for tool-using agents.", usage: "The protocol behind this site's AI assistant connector — we follow the spec whenever we expose tools to AI clients.", tags: ["MCP", "AI"] },
      { name: "Semantic Kernel", url: "https://learn.microsoft.com/semantic-kernel", desc: "Microsoft SDK for AI orchestration.", usage: "Referenced for Microsoft-stack AI orchestration in our enterprise articles.", tags: ["AI"] },
      { name: "Pinecone", url: "https://www.pinecone.io", desc: "Vector database for semantic search.", usage: "Cited in RAG tutorials for vector storage and semantic search.", tags: ["AI"] },
      { name: "Hugging Face Hub", url: "https://huggingface.co", desc: "Host of 1M+ models, datasets, and live Spaces.", usage: "The model hub we browse in our open-source LLM tutorials.", tags: ["Hugging Face", "Open Source", "LLMs"] },
      { name: "Hugging Face Transformers", url: "https://huggingface.co/docs/transformers", desc: "Unified Python API for thousands of ML models.", usage: "The Python API used in our model-loading and fine-tuning examples.", tags: ["Transformers", "Machine Learning", "Python"] },
      { name: "Ollama", url: "https://ollama.com", desc: "Run LLMs locally with a single command.", usage: "Our local-LLM tutorials run models with a single Ollama command.", tags: ["AI", "LLMs"] },
      { name: "LM Studio", url: "https://lmstudio.ai", desc: "Desktop app to discover, download, and chat with local models.", usage: "Recommended as a GUI alternative to Ollama for chatting with local models.", tags: ["AI", "LLMs"] },
      { name: "vLLM", url: "https://docs.vllm.ai", desc: "High-throughput, memory-efficient LLM serving engine.", usage: "Referenced when tutorials need high-throughput local model serving.", tags: ["AI", "LLMs"] },
      { name: "Replicate", url: "https://replicate.com", desc: "Run and fine-tune open models via API.", usage: "Cited for running open models via API without local GPU hardware.", tags: ["AI"] },
      { name: "Together AI", url: "https://www.together.ai", desc: "Open-source model APIs and fine-tuning platform.", usage: "An API platform we mention alongside Replicate in hosted-model tutorials.", tags: ["AI"] },
      { name: "Cursor", url: "https://www.cursor.com", desc: "AI-first code editor built on VS Code.", usage: "Our AI-assisted coding walkthroughs use Cursor as the AI-first editor example.", tags: ["AI", "Productivity"] },
      { name: "Continue", url: "https://www.continue.dev", desc: "Open-source AI coding assistant for any editor.", usage: "Recommended as the open-source assistant for any editor in our AI tooling articles.", tags: ["AI", "Open Source"] },
      { name: "Qdrant", url: "https://qdrant.tech", desc: "Open-source vector database for RAG pipelines.", usage: "Cited in our RAG pipeline tutorials for self-hosted vector search.", tags: ["AI", "Open Source"] },
    ],
  },
  {
    icon: Users,
    title: "Community & News",
    links: [
      { name: "Hacker News", url: "https://news.ycombinator.com", desc: "Tech and startup community discussion.", usage: "Where we gauge practitioner reaction to the tools before writing them up.", tags: [] },
      { name: "Reddit / r/CryptoCurrency", url: "https://www.reddit.com/r/CryptoCurrency", desc: "Crypto community news and discussion.", usage: "Community questions from this subreddit drive many of our crypto-safety explainers.", tags: ["Crypto", "Community"] },
      { name: "Reddit / r/ethdev", url: "https://www.reddit.com/r/ethdev", desc: "Ethereum developer community.", usage: "Developer threads here inform our smart-contract tutorials.", tags: ["Smart Contracts", "Ethereum"] },
      { name: "Stack Overflow", url: "https://stackoverflow.com", desc: "Q&A for programming and tooling.", usage: "Where we verify edge-case fixes before including commands in tutorials.", tags: [] },
      { name: "Ethereum Stack Exchange", url: "https://ethereum.stackexchange.com", desc: "Q&A for Solidity and Ethereum development.", usage: "The Q&A we consult for Solidity and EVM edge cases.", tags: ["Ethereum", "Solidity"] },
      { name: "Dev.to", url: "https://dev.to", desc: "Community blog platform for developers.", usage: "A community platform we reference in our developer-writing guides.", tags: [] },
      { name: "Hashnode", url: "https://hashnode.com", desc: "Developer blogging community.", usage: "Cited as a developer-blogging platform in our content workflow articles.", tags: [] },
      { name: "Coindesk", url: "https://www.coindesk.com", desc: "Crypto and blockchain news.", usage: "A news source for the crypto trends we contextualize in articles.", tags: ["Crypto"] },
      { name: "The Block", url: "https://www.theblock.co", desc: "Crypto research, data, and news.", usage: "Used for research and data context in our DeFi coverage.", tags: ["DeFi", "Crypto"] },
      { name: "Kaspa Discord", url: "https://discord.gg/kaspa", desc: "Official Kaspa community chat.", usage: "Where we verify node and mining questions before publishing Kaspa guides.", tags: ["Kaspa", "Mining"] },
    ],
  },
  {
    icon: BookOpen,
    title: "Learning & Docs",
    links: [
      { name: "Alison", url: "https://alison.com", desc: "Free online courses with certificates.", usage: "Alison gets a complete review on this site — free certified courses for professional development.", tags: ["Online Learning", "Free Courses", "Professional Development"] },
      { name: "freeCodeCamp", url: "https://www.freecodecamp.org", desc: "Free coding bootcamp with certifications.", usage: "Referenced in our learning-path articles for free, certification-bearing curricula.", tags: ["Online Learning", "Free Courses"] },
      { name: "The Odin Project", url: "https://www.theodinproject.com", desc: "Full-stack web development curriculum.", usage: "Recommended as the structured full-stack path in our developer-roadmap guides.", tags: ["Web Development"] },
      { name: "MDN Web Docs", url: "https://developer.mozilla.org", desc: "Mozilla web standards and API reference.", usage: "The web-standard reference behind every JavaScript and CSS explanation we publish.", tags: ["JavaScript", "Web Development"] },
      { name: "W3Schools", url: "https://www.w3schools.com", desc: "Beginner-friendly web tutorials.", usage: "Cited as a beginner-friendly companion in our web tutorials.", tags: [] },
      { name: "Khan Academy", url: "https://www.khanacademy.org/computing", desc: "Free computer science and math courses.", usage: "Referenced for CS fundamentals in our learning-resource roundups.", tags: [] },
      { name: "Coursera", url: "https://www.coursera.org", desc: "University courses and specializations.", usage: "Included in our guided-learning comparisons for university-level courses.", tags: [] },
      { name: "edX", url: "https://www.edx.org", desc: "Free and paid university-level courses.", usage: "Cited alongside Coursera in our free-education guides.", tags: [] },
      { name: "CryptoZombies", url: "https://cryptozombies.io", desc: "Learn Solidity by building a zombie game.", usage: "Recommended in our Solidity onboarding articles for gamified contract lessons.", tags: ["Solidity", "Smart Contracts"] },
      { name: "Buildspace", url: "https://buildspace.so", desc: "Project-based Web3 and AI learning.", usage: "Referenced for project-based Web3 learning in our education roundups.", tags: ["Web3"] },
      { name: "Protocol Berg", url: "https://protocol.cspr.io", desc: "Protocol-level blockchain engineering resources.", usage: "Cited for protocol-level engineering depth in our blockchain articles.", tags: ["Blockchain"] },
      { name: "Rust Book", url: "https://doc.rust-lang.org/book", desc: "Official guide to the Rust programming language.", usage: "The official Rust guide we follow in our rusty-kaspa node build tutorial.", tags: ["Rust", "Kaspa"] },
      { name: "Learn You a Haskell", url: "http://learnyouahaskell.com", desc: "Friendly introduction to functional programming.", usage: "Referenced for functional-programming concepts in our language articles.", tags: [] },
      { name: "MIT OpenCourseWare", url: "https://ocw.mit.edu", desc: "Free MIT course materials online.", usage: "Cited in our free-learning guides for university-grade material.", tags: [] },
      { name: "Roadmap.sh", url: "https://roadmap.sh", desc: "Career learning roadmaps for developers.", usage: "Recommended in career guides for structured developer learning paths.", tags: ["Career"] },
    ],
  },
  {
    icon: HardDrive,
    title: "Mining & Hardware",
    links: [
      { name: "Bitmain", url: "https://www.bitmain.com", desc: "Antminer ASIC miners for Bitcoin and Kaspa.", usage: "The Antminer references in our Kaspa and Bitcoin mining guides.", tags: ["Mining", "Bitcoin", "Kaspa"] },
      { name: "IceRiver", url: "https://iceriver.io", desc: "Kaspa (kHeavyHash) ASIC miners including the KS3 series.", usage: "We wrote a dedicated guide to powering IceRiver KS3M miners — specs, voltage, and transformer sizing.", tags: ["IceRiver", "KS3M", "Mining", "Kaspa"] },
      { name: "Goldshell", url: "https://goldshell.com", desc: "Compact ASIC miners for Kaspa, Scrypt, and more.", usage: "Cited for compact home-mining hardware in our mining setup articles.", tags: ["Mining", "Kaspa"] },
      { name: "MicroBT WhatsMiner", url: "https://www.microbt.com", desc: "High-efficiency Bitcoin ASIC miners.", usage: "Referenced in Bitcoin mining hardware comparisons.", tags: ["Mining", "Bitcoin"] },
      { name: "HiveOS", url: "https://hiveos.farm", desc: "Mining farm management and monitoring OS.", usage: "Recommended in our mining-rig management tutorials.", tags: ["Mining"] },
      { name: "Minerstat", url: "https://minerstat.com", desc: "Cloud-based mining rig monitoring and management.", usage: "Cited for rig monitoring alongside HiveOS in our mining guides.", tags: ["Mining"] },
      { name: "NiceHash", url: "https://www.nicehash.com", desc: "Hashrate marketplace for buyers and sellers.", usage: "Referenced as a hashpower marketplace in our profitability explainers.", tags: ["Mining", "Crypto"] },
      { name: "Braiins / Slush Pool", url: "https://braiins.com", desc: "Oldest Bitcoin mining pool with BOS+ firmware.", usage: "Cited for pool selection and BOS+ firmware in our Bitcoin mining coverage.", tags: ["Mining", "Bitcoin"] },
      { name: "F2Pool", url: "https://www.f2pool.com", desc: "Global multi-coin mining pool.", usage: "A pool we reference in multi-coin mining tutorials.", tags: ["Mining"] },
      { name: "ASICMinerValue", url: "https://asicminervalue.com", desc: "Compare ASIC profitability in real time.", usage: "Used for real-time ASIC profitability comparisons in our hardware guides.", tags: ["Mining"] },
      { name: "MiningRigRentals", url: "https://www.miningrigrentals.com", desc: "Rent mining rigs and hashpower by the hour.", usage: "Referenced for testing mining configurations without owning hardware.", tags: ["Mining"] },
      { name: "WhatToMine", url: "https://whattomine.com", desc: "GPU and ASIC profitability calculator.", usage: "Our go-to calculator when a tutorial needs GPU or ASIC profitability estimates.", tags: ["Mining"] },
    ],
  },
  {
    icon: Palette,
    title: "Design & UI Tools",
    links: [
      { name: "Figma", url: "https://www.figma.com", desc: "Collaborative interface design and prototyping.", usage: "Referenced in our interface-design walkthroughs for component prototyping.", tags: [] },
      { name: "FigJam", url: "https://www.figma.com/figjam", desc: "Online whiteboard for brainstorming and flows.", usage: "Cited for whiteboarding flows in our design articles.", tags: [] },
      { name: "Coolors", url: "https://coolors.co", desc: "Fast color palette generator and explorer.", usage: "Used to pick and lock palettes for our site themes in design tutorials.", tags: [] },
      { name: "Google Fonts", url: "https://fonts.google.com", desc: "Free, open-source font library with pairing.", usage: "The font library behind this site's typography, referenced in our styling guides.", tags: [] },
      { name: "Fontshare", url: "https://www.fontshare.com", desc: "Free quality fonts for personal and commercial use.", usage: "Cited as a quality free-font source in our design roundups.", tags: [] },
      { name: "Unsplash", url: "https://unsplash.com", desc: "Free high-resolution stock photography.", usage: "The stock-photo source for tutorial imagery in our publishing workflow.", tags: [] },
      { name: "Pexels", url: "https://www.pexels.com", desc: "Free stock photos and videos.", usage: "Referenced alongside Unsplash for free visuals.", tags: [] },
      { name: "Lucide Icons", url: "https://lucide.dev", desc: "Open-source, tree-shakeable icon set.", usage: "Every icon on this site is a Lucide icon — our component tutorials import them directly.", tags: [] },
      { name: "Heroicons", url: "https://heroicons.com", desc: "Hand-crafted SVG icons by the Tailwind team.", usage: "Cited as an alternative icon set in our UI articles.", tags: [] },
      { name: "Phosphor Icons", url: "https://phosphoricons.com", desc: "Flexible icon family with six weights.", usage: "Referenced for multi-weight icon needs in design walkthroughs.", tags: [] },
      { name: "Iconify", url: "https://icon-sets.iconify.design", desc: "200k+ icons from 150+ icon sets, on demand.", usage: "Used in our frontend tutorials for on-demand icon access across sets.", tags: [] },
      { name: "Tailwind UI", url: "https://tailwindui.com", desc: "Prebuilt component templates for Tailwind CSS.", usage: "Referenced when tutorials need prebuilt Tailwind component patterns.", tags: [] },
      { name: "daisyUI", url: "https://daisyui.com", desc: "Component library on top of Tailwind CSS.", usage: "Cited as a Tailwind component library option in our styling guides.", tags: [] },
      { name: "SVG Repo", url: "https://www.svgrepo.com", desc: "Free SVG vectors and icons for any project.", usage: "A vector source we mention in our asset-workflow articles.", tags: [] },
      { name: "TinyPNG", url: "https://tinypng.com", desc: "Smart PNG and JPEG image compression.", usage: "Used to compress images before publishing any tutorial.", tags: [] },
      { name: "remove.bg", url: "https://www.remove.bg", desc: "Remove image backgrounds in one click.", usage: "Cited for quick background removal in our image-editing tips.", tags: [] },
    ],
  },
  {
    icon: Server,
    title: "Self-Hosting & Homelab",
    links: [
      { name: "Home Assistant", url: "https://www.home-assistant.io", desc: "Open-source home automation with local control.", usage: "The centerpiece of our home-automation tutorials with local control.", tags: [] },
      { name: "TrueNAS", url: "https://www.truenas.com", desc: "ZFS-based NAS and storage appliance.", usage: "Referenced in our storage-server guides for ZFS-based NAS setups.", tags: [] },
      { name: "Unraid", url: "https://unraid.net", desc: "Easy NAS, VMs, and Docker app management.", usage: "Cited in homelab articles for easy NAS and Docker management.", tags: [] },
      { name: "Nextcloud", url: "https://nextcloud.com", desc: "Self-hosted file sync, share, and collaboration.", usage: "Recommended in our self-hosted file-sync walkthroughs.", tags: [] },
      { name: "Immich", url: "https://immich.app", desc: "Self-hosted photo and video backup (Google Photos alt).", usage: "Our recommended self-hosted Google Photos alternative in privacy tutorials.", tags: [] },
      { name: "Jellyfin", url: "https://jellyfin.org", desc: "Free, open-source media server.", usage: "Referenced in our open-source media-server guides.", tags: [] },
      { name: "Plex", url: "https://www.plex.tv", desc: "Media server and streaming app.", usage: "Cited alongside Jellyfin in media-server comparisons.", tags: [] },
      { name: "AdGuard Home", url: "https://adguard.com/en/adguard-home/overview.html", desc: "Network-wide ad and tracker blocking DNS.", usage: "Recommended for network-wide ad blocking in our DNS-filtering tutorials.", tags: [] },
      { name: "Portainer", url: "https://www.portainer.io", desc: "Web UI for managing Docker and Kubernetes.", usage: "Used in our Docker tutorials for a web UI over containers and stacks.", tags: ["Docker", "Containers"] },
      { name: "Traefik", url: "https://traefik.io", desc: "Modern reverse proxy and load balancer.", usage: "Cited in reverse-proxy setups in our self-hosting guides.", tags: ["Docker"] },
      { name: "Caddy", url: "https://caddyserver.com", desc: "Web server with automatic HTTPS.", usage: "Referenced for automatic-HTTPS web serving in deployment tutorials.", tags: ["HTTPS", "SSL"] },
      { name: "Vaultwarden", url: "https://github.com/dani-garcia/vaultwarden", desc: "Self-hosted Bitwarden-compatible server.", usage: "Recommended in our password-manager self-hosting guides.", tags: ["Security"] },
      { name: "BookStack", url: "https://www.bookstackapp.com", desc: "Simple, self-hosted wiki platform.", usage: "Cited as a self-hosted wiki in our knowledge-base articles.", tags: [] },
      { name: "Dockge", url: "https://github.com/louislam/dockge", desc: "Friendly Docker Compose stack manager.", usage: "Referenced for Compose-stack management in our Docker tutorials.", tags: ["Docker", "Docker Compose"] },
      { name: "Homarr", url: "https://homarr.dev", desc: "Dashboard for organizing your homelab services.", usage: "Cited in homelab dashboard setup articles.", tags: [] },
      { name: "CasaOS", url: "https://casaos.zimaspace.com", desc: "Simple personal cloud OS for home servers.", usage: "Referenced for beginner-friendly home server setups in our self-hosting series.", tags: [] },
    ],
  },
];

// Groups with slugs attached to every link
export const RESOURCE_GROUPS = RAW_GROUPS.map((g) => ({
  ...g,
  links: g.links.map((l) => ({ ...l, slug: slugify(l.name) })),
}));

// Flat, deduplicated list for detail-page lookups
export const ALL_RESOURCES = (() => {
  const seen = new Set();
  const all = [];
  for (const g of RESOURCE_GROUPS) {
    for (const l of g.links) {
      if (seen.has(l.slug)) continue;
      seen.add(l.slug);
      all.push({ ...l, group: g.title, icon: g.icon });
    }
  }
  return all;
})();