import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { POSTS } from '../../shared/blogPostsMeta.js';

const FOLDER_NAME = 'Web3Tech Blog Backup';

function buildPostMarkdown(post) {
  const tags = (post.tags || []).map((t) => `"${String(t).replace(/"/g, '\\"')}"`).join(', ');
  const safe = (s) => String(s || '').replace(/"/g, '\\"');
  return `---
title: "${safe(post.title)}"
slug: "${safe(post.slug)}"
date: "${safe(post.date)}"
author: "${safe(post.author)}"
category: "${safe(post.category)}"
image: "${safe(post.image)}"
tags: [${tags}]
---

# ${post.title || ''}

**Excerpt:** ${post.excerpt || ''}

> Read online: https://web3tech.site/blog/${post.slug}

---

This file is an automated backup generated by Web3Tech. It mirrors the post's
metadata (title, date, author, category, tags, excerpt) from the shared blog
catalog. Full article bodies are authored in the app's source and are not
included in this backup record.
`;
}

function buildMultipart(metadata, content) {
  const boundary = 'b44boundary' + Math.random().toString(36).slice(2);
  const body =
    `--${boundary}\r\n` +
    `Content-Type: application/json; charset=UTF-8\r\n\r\n` +
    JSON.stringify(metadata) + '\r\n' +
    `--${boundary}\r\n` +
    `Content-Type: text/markdown\r\n\r\n` +
    content + '\r\n' +
    `--${boundary}--`;
  return { body, contentType: `multipart/related; boundary=${boundary}` };
}

export default async function (req) {
  try {
    const base44 = createClientFromRequest(req);

    // Allow the scheduled workflow (no user session) and manual admin runs;
    // block everyone else from invoking the endpoint directly.
    let user = null;
    try {
      user = await base44.auth.me();
    } catch {}
    if (user && user.role !== 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { accessToken } = await base44.asServiceRole.connectors.getConnection('googledrive');
    const auth = { Authorization: `Bearer ${accessToken}` };

    // Find or create the backup folder.
    const findFolderRes = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
        `name='${FOLDER_NAME}' and mimeType='application/vnd.google-apps.folder' and trashed=false`
      )}&fields=files(id)`,
      { headers: auth }
    );
    const folderJson = await findFolderRes.json();
    let folderId = folderJson.files && folderJson.files[0] ? folderJson.files[0].id : null;

    if (!folderId) {
      const createFolderRes = await fetch('https://www.googleapis.com/drive/v3/files?fields=id', {
        method: 'POST',
        headers: { ...auth, 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: FOLDER_NAME, mimeType: 'application/vnd.google-apps.folder' }),
      });
      const fd = await createFolderRes.json();
      folderId = fd.id;
    }

    // List existing backup files in the folder so we update instead of duplicating.
    const listRes = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
        `'${folderId}' in parents and trashed=false`
      )}&fields=files(id,name)`,
      { headers: auth }
    );
    const listJson = await listRes.json();
    const existing = {};
    for (const f of listJson.files || []) {
      existing[f.name] = f.id;
    }

    let created = 0;
    let updated = 0;
    const errors = [];

    for (const post of POSTS) {
      const fileName = `${post.slug}.md`;
      const content = buildPostMarkdown(post);

      try {
        if (existing[fileName]) {
          const { body, contentType } = buildMultipart({ name: fileName }, content);
          const res = await fetch(
            `https://www.googleapis.com/upload/drive/v3/files/${existing[fileName]}?uploadType=multipart&fields=id`,
            { method: 'PATCH', headers: { ...auth, 'Content-Type': contentType }, body }
          );
          if (res.ok) updated++;
          else errors.push({ slug: post.slug, status: res.status, op: 'update' });
        } else {
          const { body, contentType } = buildMultipart(
            { name: fileName, mimeType: 'text/markdown', parents: [folderId] },
            content
          );
          const res = await fetch(
            'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',
            { method: 'POST', headers: { ...auth, 'Content-Type': contentType }, body }
          );
          if (res.ok) created++;
          else errors.push({ slug: post.slug, status: res.status, op: 'create' });
        }
      } catch (e) {
        errors.push({ slug: post.slug, error: e.message });
      }
    }

    return Response.json({
      status: 'ok',
      folder: folderId,
      posts: POSTS.length,
      created,
      updated,
      errors,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}